### ISSUE TITLE
Mutliple Template Matchin

### ISSUE THREAD

**Issue by nisarg182** [michaeltroger/template-matching-android#1]
Hi Michael,

Thanks for the code. If I want to detect multiple PXL Images than what should changes should be done in your code. Could you please guide. 
(I tried creating 'while' Loop but camera is opening with Black Screen.)
Thanks :)

**Comment by amrithmmh** [comment]
I have exact same question .. @nisarg182 did it work for you?

**Comment by nisarg182** [comment]
Nop,it didnt work... :(

**Comment by nisarg182** [comment]
Nop,it didnt work... :(

**Comment by nisarg182** [comment]
Nop,it didnt work... :(

**Comment by michaeltroger** [comment]
Hello!

I didn't work with OpenCV for a longer period now. However my suggestion is:
In the `MainActivity`: `Imgproc.matchTemplate(img, templ, result, match_method);` will save the result matrix. See also https://docs.opencv.org/java/2.4.2/org/opencv/imgproc/Imgproc.html#matchTemplate(org.opencv.core.Mat,%20org.opencv.core.Mat,%20org.opencv.core.Mat,%20int) 
In my example `Core.minMaxLoc(result, new Mat());` is afterwards responsible to find the minimum/maximum respectively. See also https://docs.opencv.org/java/2.4.2/org/opencv/core/Core.html#minMaxLoc(org.opencv.core.Mat,%20org.opencv.core.Mat)
Instead of finding only the best with `minMaxLoc` you would need to use another way for finding not the best, but the two best results or how much ever you search for.

Please understand that I don't have any time available currently to implement it or to give further instructions as I would need to research for myself.

**Comment by amrithmmh** [comment]
@nisarg182 please dont post the same message a 100 times!!!
